# .travis.yml
#
# To debug travis locally:
# https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally
---
sudo: false
language: ruby
services:
  - docker
cache: bundler
before_install:
  - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
  - sudo dpkg -i puppet5-release-trusty.deb
  - sudo apt-get update
  - sudo apt install -y pdk
  - make Gemfile.local
  - bundle exec pdqtest setup
script:
  - make
rvm:
  - 2.4.1
